CREATE TABLE TBL_STOCK(Product_Id VARCHAR2(6) PRIMARY KEY,Product_Name VARCHAR2(20) UNIQUE,Quantity_On_Hand NUMBER CHECK(Quantity_On_Hand >0),Reorder_Level NUMBER CHECK(Reorder_Level >0),Product_Unit_Price NUMBER CHECK(Product_Unit_Price >0));
CREATE TABLE TBL_SALES(Sales_Id VARCHAR2(6) PRIMARY KEY,Sales_Date DATE,Product_Id VARCHAR2(6),Quantity_Sold NUMBER CHECK(Quantity_Sold >0),Sales_Price_Per_Unit NUMBER CHECK(Sales_Price_Per_Unit>0),CONSTRAINT pk_fk_pid FOREIGN KEY(Product_Id) REFERENCES TBL_STOCK(Product_Id));
INSERT INTO TBL_STOCK VALUES('RE1001','REDMI NOTE 3',20,12000,5);
INSERT INTO TBL_STOCK VALUES('ip1002','Iphone 5S',10,21000,2);
INSERT INTO TBL_STOCK VALUES('PA1003','Panasonic P55',50,5500,5);
SELECT * FROM TBL_STOCK;
CREATE SEQUENCE SEQ_SALES_ID START WITH 1000 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCT_ID START WITH 1004 INCREMENT BY 1;
CREATE VIEW V_SALES_REPORT AS SELECT Sales_Id,Sales_Date,Product_Id,Product_Name,Quantity_Sold,Product_Unit_Price,Sales_Price_Per_Unit,(Sales_Price_Per_Unit - Product_Unit_Price) Profit_Amount FROM TBL_STOCK NATURAL JOIN TBL_SALES ORDER BY Profit_Amount DESC,Sales_Id ASC;